additional_commands:
  foo:
    flags:
    - BAR
    - BAZ
    kwargs:
      DEPENDS: '*'
      HEADERS: '*'
      SOURCES: '*'
autosort: true
bullet_char: '*'
dangle_parens: true
enum_char: .
line_ending: unix
line_width: 120
max_pargs_hwrap: 5
max_subgroups_hwrap: 2
separate_ctrl_name_with_space: false
separate_fn_name_with_space: false
tab_size: 4

markup:
  enable_markup: false
